title: Cherri
description: iOS Siri Shortcuts Programming Language

theme: just-the-docs
logo: "/assets/cherri_light.png"
color_scheme: cherri
callouts:
  warning:
    title: Warning
    color: yellow
  note:
    title: Note
    color: blue
  important:
    title: Important
    color: red

aux_links:
  "View Source on GitHub":
    - "//github.com/electrikmilk/cherri"
aux_links_new_tab: true

nav_external_links:
  - title: Playground
    url: https://playground.cherrilang.org/
    hide_icon: false
  - title: Code Tour
    url: https://www.youtube.com/watch?v=gU8TsI96uww
    hide_icon: false

footer_content: "Copyright &copy; Brandon Jordan. Distributed under the <a href=\"https://github.com/electrikmilk/cherri/blob/main/LICENSE\">GPL-2.0 License.</a>"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

gh_edit_link: true
gh_edit_link_text: "Contribute to this page"
gh_edit_repository: "https://github.com/electrikmilk/cherrilang.org"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"
